
project_id = "pgdzrvdwgoomjnnegkcn"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
port = 54325

[auth]
enabled = true
port = 54326

[realtime]
enabled = true
port = 54327

[functions]
[functions.send-hotel-referral-email]
verify_jwt = true
[functions.hotel-referral-webhook]
verify_jwt = true
[functions.update-admin-email]
verify_jwt = false
[functions.notify-admin-registration]
verify_jwt = false
[functions.send-join-us-notification]
verify_jwt = false

