project_id = "pgdzrvdwgoomjnnegkcn"

[auth]
enabled = true
external_url = "https://ca48e511-da23-4c95-9913-59cb1724cacc.lovableproject.com"
additional_redirect_urls = ["https://ca48e511-da23-4c95-9913-59cb1724cacc.lovableproject.com", "https://ca48e511-da23-4c95-9913-59cb1724cacc.lovableproject.com/auth/callback"]

# CRITICAL: Auth webhook configuration to intercept signup events
[auth.hook]
enabled = true
uri = "https://pgdzrvdwgoomjnnegkcn.supabase.co/functions/v1/auth-hook"
secrets = "super-secret-hook-password"

# Enable email confirmations but disable Supabase's default emails
[auth.email]
enable_signup = true
enable_confirmations = false
double_confirm_changes = false
secure_email_change_enabled = false

[functions.auth-hook]
verify_jwt = false

[storage]
enabled = true
file_size_limit = "50MB"
image_transformation = {enabled = true}

[storage.buckets.avatars]
public = true
file_size_limit = "10MB"
allowed_mime_types = ["image/jpeg", "image/png", "image/webp"]

[storage.buckets.hotel-images]
public = true
file_size_limit = "10MB"
allowed_mime_types = ["image/jpeg", "image/png", "image/webp"]

[storage.buckets.join-us-files]
public = false
file_size_limit = "50MB"
allowed_mime_types = ["application/pdf", "application/msword", "application/vnd.openxmlformats-officedocument.wordprocessingml.document", "text/plain"]

[functions.process-hotel-referral]
verify_jwt = true

[functions.batch-translate-hotels]
verify_jwt = true

[functions.batch-populate-hotel-images]
verify_jwt = true

[functions.send-notification]
verify_jwt = false

[functions.get-maps-key]
verify_jwt = false

[functions.get-user-email]
verify_jwt = true

[functions.send-password-recovery]
verify_jwt = false

[functions.emergency-admin-reset]
verify_jwt = false

[functions.custom-password-reset]
verify_jwt = false

[functions.custom-password-confirm]
verify_jwt = false

[functions.confirm-user]
verify_jwt = false