
project_id = "pgdzrvdwgoomjnnegkcn"

[auth]
enabled = true
site_url = "https://pgdzrvdwgoomjnnegkcn.supabase.co"
additional_redirect_urls = ["https://lovable.dev"]

[db]
major_version = 15

[functions.get-affinities]
verify_jwt = false

[functions.notify-admin-registration]
verify_jwt = false

[functions.remove_pending_change_field]
verify_jwt = false

[functions.export-themes]
verify_jwt = false

[functions.export-activities]
verify_jwt = false
