project_id = "pgdzrvdwgoomjnnegkcn"

[auth]
enabled = true
external_url = "https://lovable.dev"
additional_redirect_urls = ["https://lovable.dev", "https://lovable.dev/auth/callback"]

[storage]
enabled = true
file_size_limit = "50MB"
image_transformation = {enabled = true}

[storage.buckets.avatars]
public = true
file_size_limit = "10MB"
allowed_mime_types = ["image/jpeg", "image/png", "image/webp"]

[storage.buckets.hotel-images]
public = true
file_size_limit = "10MB"
allowed_mime_types = ["image/jpeg", "image/png", "image/webp"]

[storage.buckets.join-us-files]
public = false
file_size_limit = "50MB"
allowed_mime_types = ["application/pdf", "application/msword", "application/vnd.openxmlformats-officedocument.wordprocessingml.document", "text/plain"]

[functions.process-hotel-referral]
verify_jwt = false

[functions.batch-translate-hotels]
verify_jwt = false

[functions.batch-populate-hotel-images]
verify_jwt = false

[functions.send-notification]
verify_jwt = false