project_id = "pgdzrvdwgoomjnnegkcn"

[auth]
enabled = true
external_url = "https://lovable.dev"
additional_redirect_urls = ["https://lovable.dev", "https://lovable.dev/auth/callback"]

# Configure custom email delivery
[auth.email]
enable_signup = true
enable_confirmations = true
# Use custom edge function for password recovery
recovery_url = "https://pgdzrvdwgoomjnnegkcn.supabase.co/functions/v1/send-password-recovery"

[storage]
enabled = true
file_size_limit = "50MB"
image_transformation = {enabled = true}

[storage.buckets.avatars]
public = true
file_size_limit = "10MB"
allowed_mime_types = ["image/jpeg", "image/png", "image/webp"]

[storage.buckets.hotel-images]
public = true
file_size_limit = "10MB"
allowed_mime_types = ["image/jpeg", "image/png", "image/webp"]

[storage.buckets.join-us-files]
public = false
file_size_limit = "50MB"
allowed_mime_types = ["application/pdf", "application/msword", "application/vnd.openxmlformats-officedocument.wordprocessingml.document", "text/plain"]

[functions.process-hotel-referral]
verify_jwt = true

[functions.batch-translate-hotels]
verify_jwt = true

[functions.batch-populate-hotel-images]
verify_jwt = true

[functions.send-notification]
verify_jwt = false

[functions.get-maps-key]
verify_jwt = false

[functions.get-user-email]
verify_jwt = true

[functions.send-password-recovery]
verify_jwt = false

[functions.emergency-admin-reset]
verify_jwt = false