# netlify.toml - Configuration for Netlify deployments

[build]
command = "npx update-browserslist-db@latest --no-update-notifier && npm install --legacy-peer-deps && npm run build"
publish = "dist"

[build.environment]
NODE_VERSION = "18"
SKIP_GO_INSTALL = "true"

[build.processing]
skip_processing = true

[build.processing.html]
pretty_urls = true

# Cache-Control headers for different asset types
[[headers]]
for = "/*.html"
[headers.values]
Cache-Control = "no-cache, no-store, must-revalidate"
Pragma = "no-cache"
Expires = "0"

[[headers]]
for = "/assets/*.js"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/assets/*.css"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/assets/*.woff2"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.ico"
[headers.values]
Cache-Control = "public, max-age=86400"

[[headers]]
for = "/images/*"
[headers.values]
Cache-Control = "public, max-age=86400"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
