# netlify.toml - Configuration for Netlify deployments

[build]
command = "rm -rf .netlify dist .vite node_modules/.vite .next out build && npm ci --force --legacy-peer-deps && npm run build -- --force --no-cache"
publish = "dist"
ignore = ""

[build.environment]
NODE_VERSION = "18"
SKIP_GO_INSTALL = "true"
NPM_FLAGS = "--no-optional --force"
NETLIFY_SKIP_CACHE = "true"

[build.processing]
skip_processing = true

[build.processing.html]
pretty_urls = true

[build.processing.css]
bundle = true
minify = true

[[headers]]
for = "/assets/*"
[headers.values]
Cache-Control = "no-cache, no-store, must-revalidate"
Pragma = "no-cache"
Expires = "0"
Content-Type = "text/css; charset=utf-8"

[[headers]]
for = "*.css"
[headers.values]
Cache-Control = "no-cache, no-store, must-revalidate"
Pragma = "no-cache"
Expires = "0"
Content-Type = "text/css; charset=utf-8"

[[headers]]
for = "/_next/static/*"
[headers.values]
Cache-Control = "no-cache, no-store, must-revalidate"
Status = "404"


[[redirects]]
from = "/*"
to = "/index.html"
status = 200
