# netlify.toml - Configuration for Netlify deployments

[build]
command = "rm -rf .netlify dist .vite node_modules/.vite .next out build && npm ci --force --legacy-peer-deps --no-cache && npm run build -- --force --no-cache"
publish = "dist"
ignore = ""

[build.environment]
NODE_VERSION = "18"
SKIP_GO_INSTALL = "true"
NPM_FLAGS = "--no-optional --force --no-cache"
NETLIFY_SKIP_CACHE = "true"
NETLIFY_PURGE_CACHE = "true"

[build.processing]
skip_processing = true

[build.processing.html]
pretty_urls = true

[build.processing.css]
bundle = true
minify = true

# Force correct MIME types for CSS files
[[headers]]
for = "/assets/*.css"
[headers.values]
Content-Type = "text/css; charset=utf-8"
Cache-Control = "no-cache, no-store, must-revalidate, max-age=0"
Pragma = "no-cache"
Expires = "0"

[[headers]]
for = "*.css"
[headers.values]
Content-Type = "text/css; charset=utf-8"
Cache-Control = "no-cache, no-store, must-revalidate, max-age=0"
Pragma = "no-cache"
Expires = "0"

# Block all Next.js static paths with 404
[[headers]]
for = "/_next/static/*"
[headers.values]
Cache-Control = "no-cache, no-store, must-revalidate"

# Force browser cache invalidation for HTML
[[headers]]
for = "/*.html"
[headers.values]
Cache-Control = "no-cache, no-store, must-revalidate, max-age=0"
Pragma = "no-cache"
Expires = "0"

# Block Next.js paths and return 404
[[redirects]]
from = "/_next/static/*"
to = "/404"
status = 404

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
