# netlify.toml - Configuration for Netlify deployments

[build]
command = "npx update-browserslist-db@latest --no-update-notifier && npm install --legacy-peer-deps && npm run build"
publish = "dist"

[build.environment]
NODE_VERSION = "18"
SKIP_GO_INSTALL = "true"

[build.processing]
skip_processing = true

[build.processing.html]
pretty_urls = true

[[plugins]]
package = "@netlify/plugin-gatsby"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
