const [formData, setFormData] = useState({
  hotelName: "",
  propertyType: "",
  description: "",
  country: "",
  address: "",
  city: "",
  postalCode: "",
  contactName: "",
  contactEmail: "",
  contactPhone: "",
  category: "",
  stayLengths: [] as number[],
  mealPlans: [] as string[],
  roomTypes: [] as any[],
  themes: [] as string[],
  activities: [] as string[],
  faqs: [] as any[],
  terms: "",
  termsAccepted: false,
  testField: "" // ← ¡Esta línea es la que faltaba!
});