
export const TOTAL_STEPS = 5;

export const STEP_TITLES = [
  "INFORMACIÓN GENERAL",
  "PERFIL DEL HOTEL", 
  "CONDICIONES DE LA ESTANCIA",
  "PAQUETES Y TARIFAS",
  "PREGUNTAS FRECUENTES Y CONDICIONES"
];
