-- Fix security warnings by setting search_path for existing functions
ALTER FUNCTION public.is_admin(uuid) SET search_path TO 'public';
ALTER FUNCTION public.update_updated_at_column() SET search_path TO 'public';
ALTER FUNCTION public.update_hotel_available_months() SET search_path TO 'public';
ALTER FUNCTION public.get_unique_countries() SET search_path TO 'public';
ALTER FUNCTION public.sync_profile_email_verification() SET search_path TO 'public';
ALTER FUNCTION public.check_package_availability(uuid, integer) SET search_path TO 'public';
ALTER FUNCTION public.reserve_package_rooms(uuid, integer) SET search_path TO 'public';
ALTER FUNCTION public.restore_package_availability(uuid, integer) SET search_path TO 'public';
ALTER FUNCTION public.check_package_availability_enhanced(uuid, integer) SET search_path TO 'public';
ALTER FUNCTION public.reserve_package_rooms_enhanced(uuid, integer) SET search_path TO 'public';
ALTER FUNCTION public.handle_join_us_submission() SET search_path TO 'public';
ALTER FUNCTION public.restore_package_availability_enhanced(uuid, integer) SET search_path TO 'public';
ALTER FUNCTION public.generate_agent_code(text, text) SET search_path TO 'public';
ALTER FUNCTION public.get_cities_by_country(text) SET search_path TO 'public';
ALTER FUNCTION public.get_unique_property_types() SET search_path TO 'public';
ALTER FUNCTION public.get_unique_property_styles() SET search_path TO 'public';
ALTER FUNCTION public.get_price_distribution() SET search_path TO 'public';
ALTER FUNCTION public.get_themes_with_counts() SET search_path TO 'public';
ALTER FUNCTION public.get_activities_with_counts() SET search_path TO 'public';
ALTER FUNCTION public.generate_association_code(text) SET search_path TO 'public';
ALTER FUNCTION public.check_package_overlap() SET search_path TO 'public';
ALTER FUNCTION public.check_agent_hotel_eligibility(uuid, uuid) SET search_path TO 'public';
ALTER FUNCTION public.update_agent_hotel_status() SET search_path TO 'public';
ALTER FUNCTION public.set_association_code() SET search_path TO 'public';
ALTER FUNCTION public.validate_password_strength(text) SET search_path TO 'public';
ALTER FUNCTION public.check_rate_limit(text, text, integer, integer) SET search_path TO 'public';
ALTER FUNCTION public.assign_dual_roles_to_user(text) SET search_path TO 'public';
ALTER FUNCTION public.set_association_user_id() SET search_path TO 'public';
ALTER FUNCTION public.is_admin_user() SET search_path TO 'public';
ALTER FUNCTION public.has_role(text) SET search_path TO 'public';
ALTER FUNCTION public.get_my_roles() SET search_path TO 'public';
ALTER FUNCTION public.handle_new_user() SET search_path TO 'public';