-- STEP 1: Clear existing activities and affinities completely
DELETE FROM filters WHERE category IN ('activities', 'themes', 'affinities');

-- STEP 2: Insert the definitive 99 Activities list
INSERT INTO filters (category, value, source_type, jotform_field_id, is_active) VALUES
('activities', 'Agua y playa', 'jotform', '15', true),
('activities', 'Aprendizaje experiencial', 'jotform', '15', true),
('activities', 'Bachata (clases de baile)', 'jotform', '15', true),
('activities', 'Baile al aire libre', 'jotform', '15', true),
('activities', 'Baile de salón', 'jotform', '15', true),
('activities', 'Baile moderno', 'jotform', '15', true),
('activities', 'Baile tradicional', 'jotform', '15', true),
('activities', 'Baile urbano', 'jotform', '15', true),
('activities', 'Barbacoa en grupo', 'jotform', '15', true),
('activities', 'Búsqueda del tesoro', 'jotform', '15', true),
('activities', 'Caminatas guiadas', 'jotform', '15', true),
('activities', 'Campamentos temáticos', 'jotform', '15', true),
('activities', 'Cata de vinos', 'jotform', '15', true),
('activities', 'Charlas sobre cine', 'jotform', '15', true),
('activities', 'Ciclismo de montaña', 'jotform', '15', true),
('activities', 'Ciclismo recreativo', 'jotform', '15', true),
('activities', 'Clases de bachata', 'jotform', '15', true),
('activities', 'Clases de baile', 'jotform', '15', true),
('activities', 'Clases de ballet', 'jotform', '15', true),
('activities', 'Clases de cocina', 'jotform', '15', true),
('activities', 'Clases de salsa', 'jotform', '15', true),
('activities', 'Clases de tango', 'jotform', '15', true),
('activities', 'Club de lectura', 'jotform', '15', true),
('activities', 'Coleccionismo', 'jotform', '15', true),
('activities', 'Collage creativo', 'jotform', '15', true),
('activities', 'Compostaje urbano', 'jotform', '15', true),
('activities', 'Conciertos', 'jotform', '15', true),
('activities', 'Conciertos al aire libre', 'jotform', '15', true),
('activities', 'Conferencias', 'jotform', '15', true),
('activities', 'Conferencias educativas', 'jotform', '15', true),
('activities', 'Correr y jogging', 'jotform', '15', true),
('activities', 'Cultura en vivo', 'jotform', '15', true),
('activities', 'Cursos creativos', 'jotform', '15', true),
('activities', 'Cursos de idiomas', 'jotform', '15', true),
('activities', 'Debates culturales', 'jotform', '15', true),
('activities', 'Deportes de equipo', 'jotform', '15', true),
('activities', 'Deportes de raqueta', 'jotform', '15', true),
('activities', 'Deportes extremos', 'jotform', '15', true),
('activities', 'Ejercicio funcional', 'jotform', '15', true),
('activities', 'Escape room', 'jotform', '15', true),
('activities', 'Escritura creativa', 'jotform', '15', true),
('activities', 'Esnórquel', 'jotform', '15', true),
('activities', 'Espectáculos de danza', 'jotform', '15', true),
('activities', 'Espectáculos de humor', 'jotform', '15', true),
('activities', 'Espectáculos de marionetas', 'jotform', '15', true),
('activities', 'Espectáculos de ópera', 'jotform', '15', true),
('activities', 'Espectáculos de teatro', 'jotform', '15', true),
('activities', 'Espectáculos infantiles', 'jotform', '15', true),
('activities', 'Espectáculos multimedia', 'jotform', '15', true),
('activities', 'Espectáculos nocturnos', 'jotform', '15', true),
('activities', 'Espectáculos temáticos', 'jotform', '15', true),
('activities', 'Espectáculos visuales', 'jotform', '15', true),
('activities', 'Esquí o snowboard', 'jotform', '15', true),
('activities', 'Eventos astronómicos', 'jotform', '15', true),
('activities', 'Excursiones a la naturaleza', 'jotform', '15', true),
('activities', 'Festivales locales', 'jotform', '15', true),
('activities', 'Fiestas temáticas', 'jotform', '15', true),
('activities', 'Fitness y movimiento', 'jotform', '15', true),
('activities', 'Gimnasio', 'jotform', '15', true),
('activities', 'Juegos de cartas', 'jotform', '15', true),
('activities', 'Juegos de mesa', 'jotform', '15', true),
('activities', 'Juegos tradicionales', 'jotform', '15', true),
('activities', 'Juegos virtuales', 'jotform', '15', true),
('activities', 'Karaoke', 'jotform', '15', true),
('activities', 'Kayak', 'jotform', '15', true),
('activities', 'Manualidades', 'jotform', '15', true),
('activities', 'Meditación al aire libre', 'jotform', '15', true),
('activities', 'Meditación guiada', 'jotform', '15', true),
('activities', 'Montañismo', 'jotform', '15', true),
('activities', 'Murales participativos', 'jotform', '15', true),
('activities', 'Natación en piscina exterior', 'jotform', '15', true),
('activities', 'Natación en piscina interior', 'jotform', '15', true),
('activities', 'Noche de cine', 'jotform', '15', true),
('activities', 'Noche de juegos', 'jotform', '15', true),
('activities', 'Paddle surf', 'jotform', '15', true),
('activities', 'Paintball', 'jotform', '15', true),
('activities', 'Paseos a caballo', 'jotform', '15', true),
('activities', 'Paseos históricos', 'jotform', '15', true),
('activities', 'Pesca recreativa', 'jotform', '15', true),
('activities', 'Picnics organizados', 'jotform', '15', true),
('activities', 'Pilates', 'jotform', '15', true),
('activities', 'Ping pong', 'jotform', '15', true),
('activities', 'Pintura colaborativa', 'jotform', '15', true),
('activities', 'Rafting', 'jotform', '15', true),
('activities', 'Realidad virtual', 'jotform', '15', true),
('activities', 'Rutas en bicicleta', 'jotform', '15', true),
('activities', 'Rutas gastronómicas', 'jotform', '15', true),
('activities', 'Salsa (clases de baile)', 'jotform', '15', true),
('activities', 'Senderismo', 'jotform', '15', true),
('activities', 'Series de TV', 'jotform', '15', true),
('activities', 'Show de talentos', 'jotform', '15', true),
('activities', 'Tai chi', 'jotform', '15', true),
('activities', 'Talleres artísticos', 'jotform', '15', true),
('activities', 'Talleres de cerámica', 'jotform', '15', true),
('activities', 'Talleres de escritura', 'jotform', '15', true),
('activities', 'Talleres de fotografía', 'jotform', '15', true),
('activities', 'Talleres de jardinería', 'jotform', '15', true),
('activities', 'Talleres de música', 'jotform', '15', true),
('activities', 'Talleres de teatro', 'jotform', '15', true),
('activities', 'Tango (clases de baile)', 'jotform', '15', true),
('activities', 'Teatro callejero', 'jotform', '15', true),
('activities', 'Tenis', 'jotform', '15', true),
('activities', 'Tirolesa', 'jotform', '15', true),
('activities', 'Torneos de cartas', 'jotform', '15', true),
('activities', 'Torneos de videojuegos', 'jotform', '15', true),
('activities', 'Torneos deportivos', 'jotform', '15', true),
('activities', 'Videojuegos', 'jotform', '15', true),
('activities', 'Visitas a granjas', 'jotform', '15', true),
('activities', 'Visitas guiadas', 'jotform', '15', true),
('activities', 'Yoga en interior', 'jotform', '15', true),
('activities', 'Yoga en la playa', 'jotform', '15', true),
('activities', 'Zumba', 'jotform', '15', true);

-- STEP 3: Insert the definitive 113 Affinities list
INSERT INTO filters (category, value, source_type, jotform_field_id, is_active) VALUES
('affinities', 'Ajedrez', 'jotform', '16', true),
('affinities', 'Animales salvajes', 'jotform', '16', true),
('affinities', 'Arquitectura', 'jotform', '16', true),
('affinities', 'Arte contemporáneo', 'jotform', '16', true),
('affinities', 'Arte digital', 'jotform', '16', true),
('affinities', 'Arte urbano', 'jotform', '16', true),
('affinities', 'Artes marciales', 'jotform', '16', true),
('affinities', 'Astronomía', 'jotform', '16', true),
('affinities', 'Autoayuda', 'jotform', '16', true),
('affinities', 'Baile de salón', 'jotform', '16', true),
('affinities', 'Baile social', 'jotform', '16', true),
('affinities', 'Biología', 'jotform', '16', true),
('affinities', 'Cine clásico', 'jotform', '16', true),
('affinities', 'Cine contemporáneo', 'jotform', '16', true),
('affinities', 'Cocina francesa', 'jotform', '16', true),
('affinities', 'Cocina internacional', 'jotform', '16', true),
('affinities', 'Cocina italiana', 'jotform', '16', true),
('affinities', 'Cocina japonesa', 'jotform', '16', true),
('affinities', 'Cocina mexicana', 'jotform', '16', true),
('affinities', 'Cocina saludable', 'jotform', '16', true),
('affinities', 'Cocina vegana', 'jotform', '16', true),
('affinities', 'Cocina vegetariana', 'jotform', '16', true),
('affinities', 'Comedia', 'jotform', '16', true),
('affinities', 'Crecimiento personal', 'jotform', '16', true),
('affinities', 'Cultura asiática', 'jotform', '16', true),
('affinities', 'Cultura europea', 'jotform', '16', true),
('affinities', 'Cultura latina', 'jotform', '16', true),
('affinities', 'Cultura local', 'jotform', '16', true),
('affinities', 'Cultura popular', 'jotform', '16', true),
('affinities', 'Danza contemporánea', 'jotform', '16', true),
('affinities', 'Desarrollo personal', 'jotform', '16', true),
('affinities', 'Diseño gráfico', 'jotform', '16', true),
('affinities', 'Diseño industrial', 'jotform', '16', true),
('affinities', 'Ecología', 'jotform', '16', true),
('affinities', 'Economía', 'jotform', '16', true),
('affinities', 'Educación', 'jotform', '16', true),
('affinities', 'Emprendimiento', 'jotform', '16', true),
('affinities', 'Escritura creativa', 'jotform', '16', true),
('affinities', 'Esoterismo', 'jotform', '16', true),
('affinities', 'Estilo de vida saludable', 'jotform', '16', true),
('affinities', 'Filosofía', 'jotform', '16', true),
('affinities', 'Finanzas personales', 'jotform', '16', true),
('affinities', 'Fotografía', 'jotform', '16', true),
('affinities', 'Gaming competitivo', 'jotform', '16', true),
('affinities', 'Gastronomía', 'jotform', '16', true),
('affinities', 'Geografía', 'jotform', '16', true),
('affinities', 'Gestión del tiempo', 'jotform', '16', true),
('affinities', 'Historia', 'jotform', '16', true),
('affinities', 'Historia del arte', 'jotform', '16', true),
('affinities', 'Iconos musicales', 'jotform', '16', true),
('affinities', 'Idiomas', 'jotform', '16', true),
('affinities', 'Ingeniería', 'jotform', '16', true),
('affinities', 'Innovación', 'jotform', '16', true),
('affinities', 'Inteligencia artificial', 'jotform', '16', true),
('affinities', 'Inteligencia emocional', 'jotform', '16', true),
('affinities', 'Jazz', 'jotform', '16', true),
('affinities', 'Lectura y literatura', 'jotform', '16', true),
('affinities', 'Liderazgo', 'jotform', '16', true),
('affinities', 'Literatura clásica', 'jotform', '16', true),
('affinities', 'Literatura contemporánea', 'jotform', '16', true),
('affinities', 'Literatura infantil', 'jotform', '16', true),
('affinities', 'Mediación', 'jotform', '16', true),
('affinities', 'Medicina natural', 'jotform', '16', true),
('affinities', 'Mindfulness', 'jotform', '16', true),
('affinities', 'Moda', 'jotform', '16', true),
('affinities', 'Motivación', 'jotform', '16', true),
('affinities', 'Música clásica', 'jotform', '16', true),
('affinities', 'Música electrónica', 'jotform', '16', true),
('affinities', 'Música jazz', 'jotform', '16', true),
('affinities', 'Música latina', 'jotform', '16', true),
('affinities', 'Música pop', 'jotform', '16', true),
('affinities', 'Música rock', 'jotform', '16', true),
('affinities', 'Naturaleza', 'jotform', '16', true),
('affinities', 'Negocios', 'jotform', '16', true),
('affinities', 'Neurociencia', 'jotform', '16', true),
('affinities', 'Nutrición', 'jotform', '16', true),
('affinities', 'Ópera', 'jotform', '16', true),
('affinities', 'Organización personal', 'jotform', '16', true),
('affinities', 'Paternidad y maternidad', 'jotform', '16', true),
('affinities', 'Personajes históricos', 'jotform', '16', true),
('affinities', 'Pesonajes históricos', 'jotform', '16', true),
('affinities', 'Pintura', 'jotform', '16', true),
('affinities', 'Política', 'jotform', '16', true),
('affinities', 'Psicología', 'jotform', '16', true),
('affinities', 'Relaciones personales', 'jotform', '16', true),
('affinities', 'Religión y espiritualidad', 'jotform', '16', true),
('affinities', 'Repostería', 'jotform', '16', true),
('affinities', 'Responsabilidad social', 'jotform', '16', true),
('affinities', 'Salud holística', 'jotform', '16', true),
('affinities', 'Series de Netflix y Televisión', 'jotform', '16', true),
('affinities', 'Startups', 'jotform', '16', true),
('affinities', 'Teatro', 'jotform', '16', true),
('affinities', 'Tecnología', 'jotform', '16', true),
('affinities', 'Tejido y costura', 'jotform', '16', true),
('affinities', 'Teología', 'jotform', '16', true),
('affinities', 'Teoría musical', 'jotform', '16', true),
('affinities', 'Trabajo remoto', 'jotform', '16', true),
('affinities', 'Viajes', 'jotform', '16', true),
('affinities', 'Yoga y meditación', 'jotform', '16', true);