
import { FaqItem } from "../hotel-types";

export const revenueFaqs: FaqItem[] = [
  {
    question: "How does this impact our RevPAR?",
    answer: "Most partner properties see RevPAR increases of 15-30% after fully implementing the Hotel-Living model. While the nightly rate may be slightly discounted compared to peak-season short stays, the extended duration and reduced operational costs result in higher overall revenue performance. The most significant gains typically come from reducing vacant room nights during shoulder and low seasons."
  },
  {
    question: "Will we need to discount our rates significantly?",
    answer: "Not necessarily. While extended stays typically include some discount (usually 10-20% off best available rates), the focus is on value rather than deep discounting. The extended nature of the bookings, reduced turnover costs, and increased ancillary spending often make these stays more profitable even at slightly lower nightly rates."
  },
  {
    question: "How does the booking commission structure work?",
    answer: "Our commission is 12% on confirmed stays, significantly lower than most OTAs. There are no setup fees, marketing charges, or integration costs. For direct bookings generated by your marketing but processed through our platform, we offer a reduced commission of 8% to cover payment processing and platform services."
  },
  {
    question: "What about cancellations and no-shows?",
    answer: "Extended-stay bookings have significantly lower cancellation and no-show rates than traditional short stays. Our booking policy requires a 10% non-refundable deposit at the time of booking, which is credited toward the stay. This helps deter casual bookings while still being attractive to serious guests. In the rare case of no-shows, the deposit is split between the hotel and Hotel-Living."
  },
  {
    question: "How does this affect our ancillary revenue?",
    answer: "Extended-stay guests typically generate 30-50% more ancillary revenue than short-term guests through increased restaurant usage, bar spending, spa treatments, and activity participation. Our affinity programs create additional revenue opportunities through specialized offerings and partner commissions. Many hotels develop extended-stay-specific packages that bundle high-margin services."
  },
  {
    question: "Can we implement dynamic pricing for extended stays?",
    answer: "Yes, our platform supports various pricing models including seasonal rates, length-of-stay pricing tiers, and demand-based adjustments. The system allows you to set minimum and maximum thresholds to protect both value perception and profitability. Many properties implement progressive discounts that increase with stay duration."
  },
  {
    question: "What's the typical ROI timeline for partners?",
    answer: "Most properties reach positive ROI within 2-3 months after launching on our platform. Initial performance focuses on occupancy growth, with revenue optimization following as you refine your extended-stay offerings and pricing strategy. Properties that implement comprehensive affinity programs typically see faster ROI through premium positioning and higher rates."
  },
  {
    question: "How does this model perform during high season?",
    answer: "During traditional high seasons, many properties reduce their extended-stay inventory to maximize short-term booking revenue. However, some find that maintaining a portion of rooms for extended stays creates valuable inventory diversity and protection against short-term market fluctuations. Our revenue optimization tools help you find the ideal balance for your specific market conditions."
  },
  {
    question: "What financial metrics should we track to measure success?",
    answer: "Beyond the obvious RevPAR impact, important metrics include: cost per occupied room (typically lower for extended stays), departmental profit margins (especially in housekeeping and front desk), average length of stay trends, ancillary revenue per guest, repeat booking rates, and marketing cost per acquisition comparison between channels."
  }
];
