
name: Daily Code Backup

on:
  schedule:
    # Runs at 00:00 UTC every day
    - cron: '0 0 * * *'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags
      
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
      
      - name: Create Backup Branch
        run: |
          # Format date as YYYY-MM-DD
          CURRENT_DATE=$(date '+%Y-%m-%d')
          BACKUP_BRANCH="backup/${CURRENT_DATE}"
          
          # Check if branch already exists (in case of reruns)
          if git ls-remote --heads origin ${BACKUP_BRANCH} | grep -q ${BACKUP_BRANCH}; then
            echo "Backup branch ${BACKUP_BRANCH} already exists. Skipping."
          else
            echo "Creating backup branch: ${BACKUP_BRANCH}"
            git checkout -b ${BACKUP_BRANCH}
            git push origin ${BACKUP_BRANCH}
            echo "Backup completed successfully!"
          fi
